### PR TITLE
updates for new matplotlib

### PR DESCRIPTION
**Pull request by MarvinT**
addresses issue #19 
compatible with any matplotlib 2.0+

### CODE REVIEW

**Comment by diimdeep** [comment]
Looks good!

**Comment by onesuper** [comment]
Hope this PR can be merged

**Comment by rubik** [comment]
@martijnvermaat Can you merge this one and release please? The package is otherwise unusable.

**Comment by martijnvermaat** [comment]
Thanks for the contribution. The tests are failing (looks like because of some other matplotlib change) which makes it hard for me to merge. I'm more than happy to merge if the tests are fixed.

I don't use the package myself at the moment and don't really have time to look into it. If someone feels like maintaining it, feel free to fork.

**Comment by MarvinT** [comment]
Hey @martijnvermaat,

I could help maintaining it. Can you add me on pypi? https://pypi.org/user/marvint/

I'll try to look at the unit tests.

**Comment by MarvinT** [comment]
It seems the baseline pngs vary from system to system... I've tried generating them on several different machines and haven't been able to find a set that matches the travis-ci versions. Are you ok with me removing the comparison and just testing to see if the function calls complete without error?

**Comment by MarvinT** [comment]
I removed the mpl test comparison to the generated plots because they were different on every machine I built on and I never got a version that matched travis-ci. It might be possible to generate them using debug mode in travis if you really want to.

Also fixed a bunch of other small issues to get docs to build. It looks like it might be a good time to update the version number and possibly add me as a collaborator/maintainer 😉

**Comment by ErikBjare** [comment]
@martijnvermaat Please merge this and push it to pypi :heart:

**Comment by rubik** [comment]
@martijnvermaat  Can you merge this and publish a new version?

**Comment by MarvinT** [comment]
Hey all, I'm going to be taking over maintenance of calmap over on my repo: https://github.com/MarvinT/calmap/ . I'll try to push version 0.0.7 to pypi today with these fixes.

**Pull request closed without merging**
